# Generated by Django 3.0.1 on 2019-12-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rules_direction', models.IntegerField(choices=[(0, 'RULES ARE APPLIED ON THE FIRST COLUMN'), (1, 'RULES ARE APPLIED ON THE FIRST ROW')])),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(max_length=1000)),
                ('rule', models.CharField(max_length=30)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xml_measurements.Configuration')),
            ],
        ),
    ]
